"""Initial migration: create messages table with enum and tracking

Revision ID: ff8fbe143c1f
Revises: 
Create Date: 2026-05-16 19:31:40.472393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff8fbe143c1f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=250), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', name='ticket_status_enum', create_constraint=True), server_default='PENDING', nullable=False),
    sa.Column('ai_processed', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('date_added', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_updated', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    # ### end Alembic commands ###

    # Manually drop the custom PostgreSQL enum type so it doesn't get left behind
    op.execute('DROP TYPE ticket_status_enum;')
